- firmware/api/wideband_api.h
- firmware/can.cpp
- for_rusefi/wideband_can.h
> Can magic constants

- firmware/Makefile
following rusEFI pattern of warning message in case of missing submodule
> open question but probably useful

- .gitmodules
that's about https://github.com/rusefi/ChibiOS/commit/8aae3f1db3d66f4d025909f641a03c9d6c3abe1c etc
> ChibiOS: use rusefi/master.wideband branch

- firmware/Makefile
(cherry picked from commit eb20d28bad7dc936e042e0f04e8baa05b7077d26)
> More stack

- firmware/boards/f0_module/port.cpp
- firmware/boards/f0_module/wideband_board_config.h
- firmware/boards/f1_dave/port.cpp
- firmware/boards/f1_dave/wideband_board_config.h
- firmware/boards/port.h
- firmware/sampling.cpp
- firmware/wideband_config.h
(cherry picked from commit 8b713cebfca9772fa1742ef5a21cae1b9337951b)
> Prepare for multi-channel boards

- firmware/can.cpp
(cherry picked from commit 6f15807902937a766ebd4c0d4ed8729409258b10)
> can: avoid stack overflow

- .gitmodules
(cherry picked from commit 712eddf0b837bbfde8be413b4251f4d191fc93cf)
> Add OpenBLT submodule

- firmware/sampling.cpp
(cherry picked from commit 02fd9f248189e3e801b50c920e1166daa23283bc)
> GD32: ADC workaround

- firmware/boards/f1_rev2/port.cpp
@dron0gus what does this change need to turn green?
> Board Rev 2

- firmware/can_helper.cpp
Fix fir GD32 should not affect STM32.
Lets merge this until we fix it in ChibiOS.
Also fix TX timeout to align with comment.
> Can mailboxes & timeout

- firmware/Makefile
- firmware/boards/f1_rev2/wideband_layout.ld
also increase config flash area to 8K
> bootloader: make bootloader flash area reserve optional

- firmware/console/binary/tunerstudio.cpp
- firmware/console/binary/tunerstudio.h
(cherry picked from commit 3a4bd2c3f8796297dca20441ba93a810d52ea3e6)
> TS: dead code

- firmware/main.cpp
> main: do not forget to call startTunerStudioConnectivity()

- .github/workflows/build-firmware.yaml
- firmware/boards/build_f1_board.sh
Same as we produce composite DFU file we can produce composite HEX file
> Openblt composite hex

- .github/workflows/build-firmware.yaml
Smallest openblt artifact change
> Use openblt files

- firmware/boards/build_f1_board.sh
#212 and more better artifacts for github action
> Progress in F1 non-BLT artifacts

- firmware/boards/f1_dual/io/io_pins.h
(cherry picked from commit 57b3ac51770fb7676d1bd93daac9384d44f18667)
> f1_dual: remove duplicated definitions

- firmware/boards/f1_rev2/io/io_pins.h
(cherry picked from commit 10b482e759cf2f0aa0d55e53ad540737586e3991)
> f1_rev2: remove duplicated definitions

- firmware/console/binary/tunerstudio_io_serial.cpp
Instead enable it on default baudrate and wait for direct connection
(cherry picked from commit 4f2aa57bee6a50195768ffb0e7d7d2ff374048e4)
> TS: serial: do not disable serial after failed BT init attemp

- firmware/auxout.cpp
(cherry picked from commit d458a094b64de13e8a1540dc0fb4facade6b332f)
> auxout: designated initializers

- firmware/boards/f1_dual_rev1/port.cpp
(cherry picked from commit 26f12766968a1999e1f12e06720ecbc334a91add)
> f1_dual_rev1: update ADC, measure Un_sense, avoid clamping

- firmware/uart.cpp
(cherry picked from commit 9d8bbe38d1e63384ef0d66d3330363c894f2901b)
> uart: introduce TS_SECONDARY_SERIAL_PORT

- firmware/Makefile
- firmware/boards/f1_dual_rev1/wideband_board_config.h
- firmware/console/binary/tunerstudio.cpp
- firmware/indication.cpp
- firmware/indication.h
- firmware/main.cpp
(cherry picked from commit b486dfe682622c9835cf00457834cebf6e34da2f)
> indication: advanced indication with per-channel status led

- firmware/boards/f1_dual_rev1/board.c
- firmware/boards/f1_dual_rev1/mcuconf.h
- firmware/boards/f1_dual_rev1/wideband_board_config.h
This PR adjusts dual-rev1 board hardware mapping
> dual-rev1 Secondary uart settings

- firmware/boards/f1_dual_rev1/board.c
(cherry picked from commit 38037e8b46ea4f9c2dd370560e6138ed35ade2f7)
> f1_dual_rev1: fix SPI1 remap

- firmware/boards/f1_dual_rev1/wideband_layout.ld
(cherry picked from commit e9c0a26692d5f7bd8c0f1c46a2fd9b74edd223bf)
> f1_dual_rev1: fix LD file

- firmware/boards/f1_common/f1_port.cpp
- firmware/boards/port.h
- firmware/console/binary/tunerstudio.cpp
(cherry picked from commit b23b04edf24fabfd99461e7ca38ea165836645e6)
> f1_port: handle MFS errors

- firmware/flash_can.sh
(cherry picked from commit 4c877b63e44966f5373c264a3c82556ac9883761)
> Sample script to flash using OpenBLT over CAN

- firmware/boards/f1_dual_rev1/openblt/Makefile
- firmware/boards/f1_dual_rev1/openblt/blt_conf.h
- firmware/boards/f1_dual_rev1/openblt/flash_layout.c
- firmware/boards/f1_dual_rev1/openblt/main.c
- firmware/boards/f1_dual_rev1/openblt/startup_stm32f103xb.s
(cherry picked from commit 790de260f6e335a22737bb7d17d82687e620c838)
> f1_dual_rev1: OpenBLT

- firmware/console/binary/tunerstudio.cpp
- firmware/console/binary/tunerstudio.h
(cherry picked from commit 0b2d596aa1d834e6c395843b617db6b1913cb67f)
> TunerStudio: cleanup

- firmware/max3185x.cpp
(cherry picked from commit 083defaaf2dd20498939ca5ddd40195a2484c33b)
> max3185x: fix compilation warning

- firmware/pump_dac.cpp
(cherry picked from commit 4ab46ce6c48f3a7fe9ad68e4254ac38b2845c872)
> pump_dac: implement GetPumpOutputDuty() for DAC output

- firmware/wideband_config.h
@dron0gus suggest better value to speed things for the user
> Reduce heater supply stabilization delay from 3s to 0.5s

- firmware/boards/f1_common/f1_port.cpp
- firmware/max3185x.cpp
Plus https://github.com/dron0gus/ChibiOS/commit/88cef96dd5f86fc5a73e10fc5f3d13ab6030b9b2
> Fix f1 compilation

- firmware/ini/wideband_dual.ini
- firmware/max3185x.cpp
- firmware/max3185x.h
Just a cumulative update of MAX31855/6 driver.
> Max3185x update

- firmware/boards/f0_module/chconf.h
- firmware/boards/f0_module/port.cpp
- firmware/boards/f1_dual/chconf.h
- firmware/boards/f1_dual_rev1/chconf.h
- firmware/boards/f1_rev3/chconf.h
- firmware/boards/port.h
- firmware/sampling_thread.cpp
Rather than waiting on ADC, start it async then later wait on it after we do our math. That way we can be sampling at nearly 100% duty cycle, and doing our math for cycle N during sampling for cycle N+1
> pipeline ADC sampling and calculation
